### ISSUE TITLE
Error during initial build

### ISSUE THREAD

**Issue by bignamehere** [sapphi-red/vite-plugin-static-copy#13]
I am getting an error during the initial build after install.

```javascript
plugins: [
  viteStaticCopy({
    targets: [
      {
        src: './node_modules/PACKAGE/src/fonts/',
        dest: './public/fonts/'
      },
      {
        src: './node_modules/PACKAGE/src/img/',
        dest: './public/img/'
      }
    ]
  }),
  vue()
]
```

> vite build

failed to load config from C:\XYZ\DEV\training\vite.config.js
error during build:
C:\XYZ\DEV\training\node_modules\vite-plugin-static-copy\dist\index.js:32
import * as qs from "querystring";
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Object.require.extensions.<computed> [as .js] (C:\XYZ\DEV\training\node_modules\vite\dist\node\chunks\dep-f5552faa.js:75173:13)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\XYZ\DEV\training\vite.config.js:30:49)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.require.extensions.<computed> [as .js] (C:\XYZ\DEV\training\node_modules\vite\dist\node\chunks\dep-f5552faa.js:75170:20)
npm ERR! code ELIFECYCLE

**Comment by sapphi-red** [comment]
please provide a reproduction

**Comment by sapphi-red** [comment]
Closing due to lack of response
