### ISSUE TITLE
Watcher is undefined

### ISSUE THREAD

**Issue by copyhold** [sapphi-red/vite-plugin-static-copy#42]
I've found that `configureServer` is not been called probably because i'm not running a server , - just a `vite build`
```
 ERROR  error during build:                                                                                                                           10:32:32
TypeError: Cannot read properties of undefined (reading 'close')
    at Object.closeBundle (/Users/ilya/logzio/gaia-hermes-ws/node_modules/vite-plugin-static-copy/dist/index.cjs:949:21)
    at file:///Users/ilya/logzio/gaia-hermes-ws/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23660:40
```

and this is how plugin is fconfigured:
```
      plugins: [
        viteStaticCopy({
          targets: [
            { src: 'static', dest: '' },
            { src: 'external-registration', dest: 'static' },
            { src: 'assets/old-webpack-assets/**', dest: 'static/assets' },
          ],
        }),
      ],
```

am I doing smthng wrong

**Comment by sapphi-red** [comment]
That shouldn't happen because `apply: 'serve'` is set here.
https://github.com/sapphi-red/vite-plugin-static-copy/blob/08a2a9b7559c32f1c12490bc9361485406b3c534/src/serve.ts#L47

Would you create a reproduction?

**Comment by sapphi-red** [comment]
Closing due to lack of response.

**Comment by sapphi-red** [comment]
I guess this was same with https://github.com/sapphi-red/vite-plugin-static-copy/issues/63
