### ISSUE TITLE
Latest version seems to break vite build

### ISSUE THREAD

**Issue by robertjarske** [sapphi-red/vite-plugin-static-copy#69]
Got the following when using v1.0.0

```
Error:` Build failed with 1 error:
node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] "vite-plugin-static-copy" resolved to an ESM file. 

ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
```

Downgrading to v.0.17.1 fixes the issue

**Comment by sapphi-red** [comment]
1.0.0+ is ESM only. See the link in the error messsage.

**Comment by allenhwkim** [comment]
it's used as import, but it seems not that simple as it declared.
I also downgraded to 0.17. which support cjs in its build.

if this is not supported, I may need to use copy command or other plugin instead.
```

    vite.config.js:2:31:
      2 │ import { viteStaticCopy } from 'vite-plugin-static-copy';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/allenkim/projects/elements-x/vite.config.js
=> Failed to build the preview
Error: Build failed with 1 error:
node_modules/vite/node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] "vite-plugin-static-copy" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
    at failureErrorWithLog (./node_modules/vite/node_modules/esbuild/lib/main.js:1650:15)
    at ./node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (./node_modules/vite/node_modules/esbuild/lib/main.js:1485:45)
    at buildResponseToResult (./node_modules/vite/node_modules/esbuild/lib/main.js:1056:7)
    at ./node_modules/vite/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (./node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (./node_modules/vite/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (./node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)

```

**Comment by Lonli-Lokli** [comment]
Have same error with `vite5` and latest `Nx`
